### ISSUE TITLE
Error on npm run dev

### ISSUE THREAD

**Issue by l8te** [marcamos/jet#53]
I've tried using jet as a template and by cloning it, and in both cases I get an error on `npm run dev`. I'm following the steps in the readme. I saw https://github.com/marcamos/jet/issues/33#issue-757375236 and thought I might be having the same problem, but on closer inspection it's a different error. I'm on node 14.16.0. Let me know if there's any other information I can provide. Thanks!

`C:\Users\Lee\Documents\Dev\jet>npm run dev`

`> jet@2.0.0 dev C:\Users\Lee\Documents\Dev\jet`
`> npm run clean && postcss src/css/tailwind.css > src/css/styles.css && eleventy --serve`

`> jet@2.0.0 clean C:\Users\Lee\Documents\Dev\jet`
`> rm -rf public src/css/styles.css`

```
'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jet@2.0.0 clean: `rm -rf public src/css/styles.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jet@2.0.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lee\AppData\Roaming\npm-cache\_logs\2021-03-06T02_52_28_894Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jet@2.0.0 dev: `npm run clean && postcss src/css/tailwind.css > src/css/styles.css && eleventy --serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jet@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lee\AppData\Roaming\npm-cache\_logs\2021-03-06T02_52_28_922Z-debug.log
```

**Comment by donspaulding** [comment]
I'm not affiliated with this project at all, just checking it out like you are.  But it seems like your issue is that the `clean` script inside of `package.json` is using the `rm` command, which isn't available on Windows (it's a Unix/Linux command).

Can you try editing the package.json and replace the `rm-rf public src/css/styles.css` with `rd /s /q .\public; del /f /q .\src\css\styles.css`?  I've not tested it (I'm not using Windows) and I don't know what other windows-specific problems you're likely to run into, but that might get you one step further down the path.

**Comment by ryanccn** [comment]
This is an issue with Windows not having the `rm` command that UNIX & Linux do have.

You can try using [rimraf](https://www.npmjs.com/package/rimraf) instead of the original command:

```sh
$ npm i rimraf
```

and then just change the `clean` command from `rm -rf` to `rimraf`.

`rimraf` works cross-platform, and we'll think of using `rimraf` in the template itself in order to ensure compatibility.

Thanks for trying out jet!

**Comment by ryanccn** [comment]
migrated to `rimraf` at dfda8e90bf5b4a077ae6dbabf9410c1a6c6d8165 😄

**Comment by marcamos** [comment]
Ah! Sorry everybody! As a macOS-only user, it never dawned on me that `rm` would be an issue.

I’m a bad steward of OSS 🥴

Thank you for bringing this to our attention, and thank you, @ryanccn, for making it better.

**Comment by l8te** [comment]
Works perfectly-- thank you all!
